title: 智理校园——面向AIGC时代的高校学术合规与科研安全审计平台
page-top-title: 智理校园
top-section-bg-text: Artificial Intelligence for campus
home-subtitle: 智理校园
home-md: # 这里将在后续步骤中清空
copyright-text: '&copy; 智理校园 2026. All Rights Reserved.'
